#!../../../bin/exe/lua
-- build or serve an nginx version of an app

local apps=require("apps")
apps.setpaths(nil,{apps.find_bin()})

local bake_ngx=require("wetgenes.bake.ngx")



local tab={"release"}
tab.arg={...}

tab.cd_out="../../../www/ngx"

tab.ngx_user="wet"
--tab.ngx_user="kriss"

tab.ngx_listen="80"

--tab.ngx_debug=""
--tab.ngx_debug="debug"

bake_ngx.build(tab)

